apiVersion: v1
kind: Service
metadata:
  name: bar
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 80
  selector:
    app: bar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bar
  template:
    metadata:
      labels:
        app: bar
    spec:
      containers:
      - image: krancour/nginx:1.23.4
        name: nginx
      imagePullSecrets:
      - name: regcred
